name: Test, Build & Push

on:
  push:
    branches:
      - error-handling
  pull_request:
    branches:
      - develop

  build:
    runs-on: ubuntu-latest

jobs:
  api_job:
    name: Test, Build and Push API

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: sbt test

      - name: Run integration tests
        run: sbt it:test

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: europe-west4-docker.pkg.dev/froedevrolijk-world/world-docker-registry/world-api:0.1

  frontend_job:
    name: Build and Push Frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
#          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: europe-west4-docker.pkg.dev/froedevrolijk-world/world-docker-registry/world-frontend:0.1